version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - fullstackjs
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - fullstackjs
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    links:
      - db
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - fullstackjs
    depends_on:
      - db
networks:
  fullstackjs:
    driver: bridge
